SCREEN_WIDTH = 0
SCREEN_HEIGHT = 0

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 50
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

BOOST_MULTIPLIER = 1.1
BOOST_DURATION = 2
BOOST_COOLDOWN = 5

SHOT_RADIUS = 5

